import Notebook from "../models/Notebook.js";
import mongoose from "mongoose";
import Guide from "../models/Guide.js";
import PlantTemplate from "../models/PlantTemplate.js";
import { ok, created, noContent } from "../utils/ApiResponse.js";
import { asyncHandler } from "../utils/asyncHandler.js";
import { AppError } from "../utils/AppError.js";
import {
  sendStageWarningNotification,
  sendStageSkippedNotification,
  sendStageOverdueNotification,
} from "./notificationController.js";
import {
  getDaysDifferenceVN,
  toVietnamMidnight,
  getVietnamToday,
} from "../utils/timezone.js";

// ==========================================
// HELPER FUNCTIONS (from services)
// ==========================================

/**
 * Tính số ngày từ startDate đến endDate (theo giờ Việt Nam UTC+7)
 * Sử dụng helper từ timezone.js
 */
const getDaysDifference = getDaysDifferenceVN;

/**
 * Tính stage end date dựa trên planted_date và stage.day_end (theo giờ Việt Nam UTC+7)
 */
const getStageEndDate = (plantedDate, stageEndDay) => {
  const endDate = new Date(plantedDate);
  endDate.setDate(endDate.getDate() + stageEndDay - 1);
  return toVietnamMidnight(endDate);
};

/**
 * Kiểm tra xem notification đã được gửi chưa
 */
const hasNotificationBeenSent = (notificationsSent, type, missedDay) => {
  return notificationsSent?.some((n) => n.type === type && n.day === missedDay);
};

/**
 * Lấy template phù hợp với notebook (dựa trên guide's plant_group)
 */
const getTemplateForNotebook = async (notebookId) => {
  const notebook = await Notebook.findById(notebookId).populate("guide_id");

  if (!notebook) {
    throw new AppError("Không tìm thấy nhật ký", 404);
  }

  if (notebook.template_id) {
    const template = await PlantTemplate.findById(notebook.template_id);
    return template;
  }

  if (notebook.guide_id && notebook.guide_id.plant_group) {
    const template = await PlantTemplate.findOne({
      plant_group: notebook.guide_id.plant_group,
      status: "active",
    }).sort({ usage_count: -1 });

    return template;
  }

  return null;
};

/**
 * Gán template cho notebook
 */
const assignTemplateToNotebook = async (notebookId, templateId) => {
  const notebook = await Notebook.findById(notebookId);
  const template = await PlantTemplate.findById(templateId);

  if (!notebook) {
    throw new AppError("Không tìm thấy nhật ký", 404);
  }

  if (!template) {
    throw new AppError("Không tìm thấy template", 404);
  }

  notebook.template_id = templateId;

  notebook.stages_tracking = template.stages.map((stage, index) => ({
    stage_number: stage.stage_number,
    stage_name: stage.name,
    started_at: index === 0 ? notebook.planted_date : null,
    is_current: index === 0,
  }));

  notebook.current_stage = 1;

  await notebook.updateProgress(template.stages);

  await notebook.save();

  template.usage_count += 1;
  await template.save();

  await generateDailyChecklist(notebookId);

  return notebook;
};

/**
 * Tạo daily checklist từ template's autogenerated_tasks
 */
export const generateDailyChecklist = async (notebookId) => {
  const notebook = await Notebook.findById(notebookId).populate("template_id");

  if (!notebook || !notebook.template_id) {
    return null;
  }

  const template = notebook.template_id;
  const currentStage = template.stages.find(
    (s) => s.stage_number === notebook.current_stage
  );

  if (!currentStage) {
    return null;
  }

  const today = getVietnamToday();

  // Kiểm tra xem đã đến ngày bắt đầu của stage chưa
  const currentDay = notebook.current_day || 1;
  if (currentDay < currentStage.day_start) {
    console.log(
      `⏳ Stage ${notebook.current_stage} chưa bắt đầu (current_day: ${currentDay}, day_start: ${currentStage.day_start})`
    );
    // Trả về checklist rỗng vì chưa đến ngày bắt đầu stage
    notebook.daily_checklist = [];
    notebook.last_checklist_generated = today;
    await notebook.save();
    return [];
  }

  // Kiểm tra nếu đã tạo checklist hôm nay rồi
  const lastGenerated = notebook.last_checklist_generated
    ? toVietnamMidnight(notebook.last_checklist_generated)
    : null;

  if (lastGenerated && lastGenerated.getTime() === today.getTime()) {
    return notebook.daily_checklist;
  }

  // ✅ SANG NGÀY MỚI → Xử lý overdue cho tasks ngày hôm qua
  if (lastGenerated && lastGenerated.getTime() < today.getTime()) {
    const currentStageTracking = notebook.stages_tracking.find(
      (s) => s.stage_number === notebook.current_stage
    );

    if (currentStageTracking) {
      // Đếm số task chưa hoàn thành của ngày hôm qua
      const incompleteTasks = notebook.daily_checklist.filter(
        (task) => !task.is_completed && task.status === "pending"
      );

      if (incompleteTasks.length > 0) {
        console.log(
          `⚠️ Found ${incompleteTasks.length} incomplete tasks on ${
            lastGenerated.toISOString().split("T")[0]
          } — moving to overdue_tasks`
        );

        // Initialize overdue_tasks array if missing
        if (!currentStageTracking.overdue_tasks) {
          currentStageTracking.overdue_tasks = [];
        }

        // Move each incomplete task into stageTracking.overdue_tasks
        incompleteTasks.forEach((task) => {
          currentStageTracking.overdue_tasks.push({
            task_name: task.task_name,
            description: task.description,
            priority: task.priority || "medium",
            frequency: task.frequency || "daily",
            is_completed: task.is_completed || false,
            original_date: lastGenerated,
            status: "overdue",
            overdue_at: today,
          });
        });

        // Log moved task names for debugging
        console.log(
          `➡️ Moved tasks to overdue: ${incompleteTasks
            .map((t) => t.task_name)
            .join(", ")}`
        );

        // Lưu overdue_summary (use total persisted overdue_tasks length to avoid overwriting previous counts)
        const totalOverdueCount = currentStageTracking.overdue_tasks.length;
        currentStageTracking.overdue_summary = {
          date: lastGenerated,
          overdue_count: totalOverdueCount,
          ready_to_notify: true,
        };

        console.log(
          `📊 Overdue summary saved: ${totalOverdueCount} total overdue tasks (added ${incompleteTasks.length})`
        );
      }
    }
  }

  const daysInStage =
    Math.floor(notebook.current_day) - currentStage.day_start + 1;

  const currentStageTracking = notebook.stages_tracking
    ? notebook.stages_tracking.find(
        (s) => s.stage_number === notebook.current_stage
      )
    : null;

  const newChecklist = (
    currentStage.autogenerated_tasks ||
    currentStage.daily_tasks ||
    []
  )
    .filter((task) => {
      // Always show daily tasks
      if (task.frequency === "daily") return true;

      // One-time tasks: show only on first day of stage if not already completed
      if (task.frequency === "once") {
        const alreadyCompleted = currentStageTracking?.completed_tasks?.some(
          (t) => t.task_name === task.task_name
        );
        return !alreadyCompleted && daysInStage === 1;
      }

      // Interval-based tasks: prefer last completion date if available
      const intervalMap = {
        every_2_days: 2,
        every_3_days: 3,
        weekly: 7,
      };

      const interval = intervalMap[task.frequency];
      if (!interval) return false;

      // Find last completed entry for this task in current stage
      const lastCompleted = currentStageTracking?.completed_tasks
        ? currentStageTracking.completed_tasks
            .filter((t) => t.task_name === task.task_name)
            .reduce((latest, t) => {
              if (!latest) return t;
              return new Date(t.completed_at) > new Date(latest.completed_at)
                ? t
                : latest;
            }, null)
        : null;

      if (lastCompleted && lastCompleted.completed_at) {
        const daysSinceLast = getDaysDifference(
          lastCompleted.completed_at,
          today
        );
        // Show when days since last completion is >= interval and matches the interval cadence
        return daysSinceLast >= interval && daysSinceLast % interval === 0;
      }

      // Fallback to original stage-based cadence if never completed in this stage
      return daysInStage % interval === 0;
    })
    .map((task) => ({
      task_name: task.task_name,
      description: task.description,
      priority: task.priority,
      frequency: task.frequency,
      is_completed: false,
      status: "pending", // ✅ Set default status
    }));

  notebook.daily_checklist = newChecklist;
  notebook.last_checklist_generated = today;
  await notebook.save();

  return newChecklist;
};

/**
 * Cập nhật stage hiện tại
 */
const updateCurrentStage = async (notebookId, newStageNumber) => {
  const notebook = await Notebook.findById(notebookId).populate("template_id");

  if (!notebook || !notebook.template_id) {
    throw new AppError("Không tìm thấy nhật ký hoặc template", 404);
  }

  const template = notebook.template_id;

  if (newStageNumber > template.stages.length) {
    throw new AppError("Số stage không hợp lệ", 400);
  }

  const oldStageIndex = notebook.stages_tracking.findIndex(
    (s) => s.stage_number === notebook.current_stage
  );
  if (oldStageIndex !== -1) {
    notebook.stages_tracking[oldStageIndex].is_current = false;
    notebook.stages_tracking[oldStageIndex].completed_at = new Date();
  }

  const newStageIndex = notebook.stages_tracking.findIndex(
    (s) => s.stage_number === newStageNumber
  );
  if (newStageIndex !== -1) {
    notebook.stages_tracking[newStageIndex].is_current = true;
    notebook.stages_tracking[newStageIndex].started_at = new Date();
  }

  notebook.current_stage = newStageNumber;

  await notebook.updateProgress(template.stages);

  await notebook.save();

  await generateDailyChecklist(notebookId);

  return notebook;
};

/**
 * Kiểm tra và xử lý trạng thái stage của notebook (stage monitoring)
 */
export const checkNotebookStageStatus = async (notebook) => {
  try {
    if (!notebook.populated("template_id")) {
      await notebook.populate("template_id");
    }

    if (!notebook.template_id || !notebook.template_id.stages) {
      console.log(`⚠️ Notebook ${notebook._id} không có template`);
      return;
    }

    const template = notebook.template_id;
    const today = getVietnamToday();

    const currentStageTracking = notebook.stages_tracking.find(
      (s) => s.stage_number === notebook.current_stage
    );

    if (!currentStageTracking) {
      console.log(
        `⚠️ Không tìm thấy stage_tracking cho stage ${notebook.current_stage}`
      );
      return;
    }

    if (
      currentStageTracking.status === "completed" ||
      currentStageTracking.status === "skipped"
    ) {
      console.log(
        `✅ Stage ${notebook.current_stage} đã ${currentStageTracking.status}, bỏ qua`
      );
      return;
    }

    const templateStage = template.stages.find(
      (s) => s.stage_number === notebook.current_stage
    );

    if (!templateStage) {
      console.log(
        `⚠️ Không tìm thấy template stage cho stage ${notebook.current_stage}`
      );
      return;
    }

    const stageEndDate = getStageEndDate(
      notebook.planted_date,
      templateStage.day_end
    );
    const daysAfterEnd = getDaysDifference(stageEndDate, today);

    console.log(
      `📅 Notebook: ${notebook.notebook_name} | Stage: ${
        templateStage.name
      } | End Date: ${
        stageEndDate.toISOString().split("T")[0]
      } | Days After End: ${daysAfterEnd}`
    );

    if (daysAfterEnd <= 0) {
      console.log(`✅ Stage ${notebook.current_stage} còn trong thời hạn`);
      return;
    }

    const missedDays = daysAfterEnd;
    const safeDelayDays = template.rules?.safe_delay_days || 2;
    const autoSkip = template.rules?.auto_skip ?? true;

    console.log(
      `⚠️ Stage ${notebook.current_stage} đã trễ ${missedDays} ngày (safe_delay: ${safeDelayDays})`
    );

    currentStageTracking.missed_days = missedDays;

    if (missedDays <= safeDelayDays) {
      if (
        !hasNotificationBeenSent(
          currentStageTracking.notifications_sent,
          "warning",
          missedDays
        )
      ) {
        await sendStageWarningNotification({
          userId: notebook.user_id,
          notebookId: notebook._id,
          notebookName: notebook.notebook_name,
          stageNumber: notebook.current_stage,
          stageName: templateStage.name,
          missedDays,
          safeDelayDays,
        });

        if (!currentStageTracking.notifications_sent) {
          currentStageTracking.notifications_sent = [];
        }
        currentStageTracking.notifications_sent.push({
          type: "warning",
          day: missedDays,
          sent_at: new Date(),
        });

        if (currentStageTracking.status !== "overdue") {
          currentStageTracking.status = "overdue";
        }

        await notebook.save();
        console.log(
          `📧 Đã gửi cảnh báo lần ${missedDays} cho stage ${notebook.current_stage}`
        );
      } else {
        console.log(`⏭️ Đã gửi cảnh báo cho missedDay ${missedDays}, bỏ qua`);
      }
    } else {
      if (
        !hasNotificationBeenSent(
          currentStageTracking.notifications_sent,
          "exceeded",
          missedDays
        )
      ) {
        if (autoSkip) {
          currentStageTracking.status = "skipped";
          currentStageTracking.completed_at = new Date();
          currentStageTracking.is_current = false;

          await sendStageSkippedNotification({
            userId: notebook.user_id,
            notebookId: notebook._id,
            notebookName: notebook.notebook_name,
            stageNumber: notebook.current_stage,
            stageName: templateStage.name,
            missedDays,
            safeDelayDays,
          });

          const nextStageNumber = notebook.current_stage + 1;
          if (nextStageNumber <= template.stages.length) {
            const nextStageTracking = notebook.stages_tracking.find(
              (s) => s.stage_number === nextStageNumber
            );
            if (nextStageTracking) {
              nextStageTracking.is_current = true;
              nextStageTracking.started_at = new Date();
              nextStageTracking.status = "active";
            }
            notebook.current_stage = nextStageNumber;

            console.log(
              `⏭️ Tự động skip stage ${templateStage.stage_number}, chuyển sang stage ${nextStageNumber}`
            );
          } else {
            console.log(`🏁 Đã hết stage, không thể chuyển stage tiếp theo`);
          }

          if (!currentStageTracking.notifications_sent) {
            currentStageTracking.notifications_sent = [];
          }
          currentStageTracking.notifications_sent.push({
            type: "exceeded",
            day: missedDays,
            sent_at: new Date(),
          });

          await notebook.save();
        } else {
          currentStageTracking.status = "overdue";

          await sendStageOverdueNotification({
            userId: notebook.user_id,
            notebookId: notebook._id,
            notebookName: notebook.notebook_name,
            stageNumber: notebook.current_stage,
            stageName: templateStage.name,
            missedDays,
            safeDelayDays,
          });

          if (!currentStageTracking.notifications_sent) {
            currentStageTracking.notifications_sent = [];
          }
          currentStageTracking.notifications_sent.push({
            type: "exceeded",
            day: missedDays,
            sent_at: new Date(),
          });

          await notebook.save();
          console.log(
            `🚨 Stage ${notebook.current_stage} đã quá hạn, yêu cầu can thiệp thủ công`
          );
        }
      } else {
        console.log(`⏭️ Đã xử lý exceeded cho missedDay ${missedDays}, bỏ qua`);
      }
    }
  } catch (error) {
    console.error(`❌ Lỗi khi check notebook ${notebook._id}:`, error);
  }
};

/**
 * Đánh dấu hoàn thành task trong checklist
 */
const completeChecklistTask = async (notebookId, taskName) => {
  const notebook = await Notebook.findById(notebookId).populate("template_id");

  if (!notebook) {
    throw new AppError("Không tìm thấy nhật ký", 404);
  }

  const task = notebook.daily_checklist.find((t) => t.task_name === taskName);

  if (!task) {
    throw new AppError("Không tìm thấy công việc", 404);
  }

  task.is_completed = !task.is_completed;
  task.completed_at = task.is_completed ? new Date() : null;
  task.status = task.is_completed ? "completed" : "pending"; // ✅ Update status

  const currentStageTracking = notebook.stages_tracking.find(
    (s) => s.stage_number === notebook.current_stage
  );

  if (currentStageTracking) {
    if (task.is_completed) {
      const alreadyCompleted = currentStageTracking.completed_tasks?.some(
        (t) => t.task_name === taskName
      );

      if (!alreadyCompleted) {
        if (!currentStageTracking.completed_tasks) {
          currentStageTracking.completed_tasks = [];
        }
        currentStageTracking.completed_tasks.push({
          task_name: taskName,
          completed_at: new Date(),
        });
      }
    } else {
      if (currentStageTracking.completed_tasks) {
        currentStageTracking.completed_tasks =
          currentStageTracking.completed_tasks.filter(
            (t) => t.task_name !== taskName
          );
      }
    }
  }

  if (notebook.template_id && notebook.template_id.stages) {
    await notebook.updateProgress(notebook.template_id.stages);
    console.log(`📊 Progress updated: ${notebook.progress}%`);
    console.log(
      `📋 Completed tasks in current stage: ${
        currentStageTracking?.completed_tasks?.length || 0
      }`
    );
  }

  if (currentStageTracking) {
    const todayDate = getVietnamToday();
    const today = todayDate.toISOString().split("T")[0];

    console.log(
      `🔍 Checking daily_logs for stage ${notebook.current_stage} on ${today}`
    );

    let dailyLog = currentStageTracking.daily_logs?.find(
      (log) => log.date?.toISOString().split("T")[0] === today
    );

    if (!dailyLog) {
      if (!currentStageTracking.daily_logs) {
        currentStageTracking.daily_logs = [];
      }
      dailyLog = {
        date: todayDate,
        daily_progress: 0,
      };
      currentStageTracking.daily_logs.push(dailyLog);
      console.log(`➕ Created new daily_log for ${today}`);
    } else {
      console.log(
        `✅ Found existing daily_log for ${today}: ${dailyLog.daily_progress}%`
      );
    }

    const todayTasks = notebook.daily_checklist || [];
    const completedTodayTasks = todayTasks.filter((t) => t.is_completed).length;
    const totalTodayTasks = todayTasks.length;

    if (totalTodayTasks > 0) {
      dailyLog.daily_progress = Math.round(
        (completedTodayTasks / totalTodayTasks) * 100
      );
      console.log(
        `📅 Daily progress for ${today}: ${dailyLog.daily_progress}% (${completedTodayTasks}/${totalTodayTasks})`
      );
    }
  } else {
    console.warn(
      `⚠️ No currentStageTracking found for stage ${notebook.current_stage}`
    );
  }

  if (currentStageTracking && notebook.template_id) {
    const stageCompletion = await notebook.getCurrentStageCompletion();
    console.log(`🎯 Current stage completion: ${stageCompletion}%`);

    if (stageCompletion >= 100 && !currentStageTracking.completed_at) {
      currentStageTracking.completed_at = new Date();
      console.log(`✅ Stage ${notebook.current_stage} marked as COMPLETED`);

      await notebook.updateProgress(notebook.template_id.stages);
      console.log(`🌱 Plant progress updated: ${notebook.progress}%`);
    }
  }

  await notebook.save();

  return notebook;
};

/**
 * Lấy tất cả observations của stage hiện tại
 * CHỈ trả về observations nếu đang ở ngày cuối của giai đoạn
 */
const getCurrentStageObservations = async (notebookId) => {
  const notebook = await Notebook.findById(notebookId).populate("template_id");

  if (!notebook || !notebook.template_id) {
    return [];
  }

  const template = notebook.template_id;
  const currentStage = template.stages.find(
    (s) => s.stage_number === notebook.current_stage
  );

  if (!currentStage) {
    return [];
  }

  // Kiểm tra xem có phải ngày cuối của giai đoạn không
  const currentDay = notebook.current_day || 1;
  const isLastDayOfStage = currentDay === currentStage.day_end;

  // Nếu stage đã completed thì không trả về observation required nữa
  const stageTracking = notebook.stages_tracking.find(
    (s) => s.stage_number === notebook.current_stage
  );
  if (stageTracking && stageTracking.status === "completed") {
    // Trả về danh sách observation đã ghi nhận (có value=true)
    return (
      stageTracking.observations?.map((obs) => ({
        key: obs.key,
        value: obs.value,
        observed_at: obs.observed_at,
        completed: true,
      })) || []
    );
  }
  // CHỈ trả về observations nếu đang ở ngày cuối
  if (!isLastDayOfStage) {
    return [];
  }
  // Trả về danh sách observation required, kèm trạng thái đã hoàn thành nếu có
  return (currentStage?.observation_required || []).map((obsReq) => {
    const found = stageTracking?.observations?.find(
      (o) => o.key === obsReq.key
    );
    return {
      ...obsReq,
      value: found?.value ?? false,
      observed_at: found?.observed_at ?? null,
      completed: !!found?.value,
    };
  });
};

/**
 * Cập nhật observation cho stage hiện tại
 */
export const updateStageObservation = async (
  notebookId,
  observationKey,
  value
) => {
  const notebook = await Notebook.findById(notebookId).populate("template_id");

  if (!notebook) {
    throw new AppError("Không tìm thấy nhật ký", 404);
  }

  const stageTracking = notebook.stages_tracking.find(
    (s) => s.stage_number === notebook.current_stage
  );

  if (!stageTracking) {
    throw new AppError("Không tìm thấy stage tracking", 404);
  }

  const existingObs = stageTracking.observations.find(
    (o) => o.key === observationKey
  );

  if (existingObs) {
    existingObs.value = value;
    existingObs.observed_at = new Date();
  } else {
    stageTracking.observations.push({
      key: observationKey,
      value: value,
      observed_at: new Date(),
    });
  }

  await notebook.save();

  // ✅ Kiểm tra xem tất cả observations đã hoàn thành chưa
  if (notebook.template_id && notebook.template_id.stages) {
    const currentTemplateStage = notebook.template_id.stages.find(
      (s) => s.stage_number === notebook.current_stage
    );

    if (currentTemplateStage && currentTemplateStage.observation_required) {
      const requiredObservations = currentTemplateStage.observation_required;
      const completedObservations = stageTracking.observations.filter(
        (obs) => obs.value === true
      );

      console.log(
        `📊 Observations: ${completedObservations.length}/${requiredObservations.length} completed`
      );

      // Nếu tất cả observations bắt buộc đã hoàn thành (value = true)
      if (completedObservations.length >= requiredObservations.length) {
        console.log(
          `✅ All observations completed for stage ${notebook.current_stage}`
        );

        // Đánh dấu stage hiện tại hoàn thành
        stageTracking.completed_at = new Date();
        stageTracking.status = "completed";

        // Cập nhật progress
        await notebook.updateProgress(notebook.template_id.stages);

        // Chuyển sang stage tiếp theo nếu có
        const nextStageNumber = notebook.current_stage + 1;
        if (nextStageNumber <= notebook.template_id.stages.length) {
          console.log(`🔄 Auto-switching to stage ${nextStageNumber}`);

          // Tắt current flag của stage hiện tại
          stageTracking.is_current = false;

          // Bật current flag cho stage tiếp theo
          const nextStageTracking = notebook.stages_tracking.find(
            (s) => s.stage_number === nextStageNumber
          );

          if (nextStageTracking) {
            nextStageTracking.is_current = true;
            nextStageTracking.started_at = new Date();
            nextStageTracking.status = "active";
          }

          // Cập nhật current_stage
          notebook.current_stage = nextStageNumber;

          // Không tạo checklist ngay, chỉ tạo khi sang ngày mới
          notebook.daily_checklist = [];
          await notebook.save();

          console.log(
            `✅ Stage switched to ${nextStageNumber} successfully (checklist will be generated on next day)`
          );
        } else {
          console.log(`🏁 All stages completed!`);
          await notebook.save();
        }
      } else {
        await notebook.save();
      }
    } else {
      await notebook.save();
    }
  }

  return notebook;
};

/**
 * Tính stage hiện tại dựa trên số ngày đã trồng
 */
const calculateCurrentStage = async (notebookId) => {
  const notebook = await Notebook.findById(notebookId).populate("template_id");

  if (!notebook || !notebook.template_id) {
    return null;
  }

  const template = notebook.template_id;
  const daysPlanted = notebook.current_day;

  const stageInfo = template.getStageByDay(daysPlanted);

  if (stageInfo && stageInfo.stage_number !== notebook.current_stage) {
    await updateCurrentStage(notebookId, stageInfo.stage_number);
  }

  return stageInfo;
};

// ==========================================
// CONTROLLER EXPORTS
// ==========================================

// 📘 Lấy tất cả notebook của user
export const getAllByUser = asyncHandler(async (req, res) => {
  const notebooks = await Notebook.find({
    user_id: req.user.id,
    status: { $ne: "deleted" },
  })
    .populate("guide_id", "title category difficulty estimatedTime")
    .populate("template_id", "template_name plant_group status stages")
    .sort({ createdAt: -1 });

  return ok(
    res,
    notebooks,
    { count: notebooks.length },
    "Fetched all notebooks successfully"
  );
});

// 📗 Lấy chi tiết notebook theo ID
export const getNotebookById = asyncHandler(async (req, res) => {
  const { id } = req.params;
  const notebook = await Notebook.findOne({
    _id: id,
    user_id: req.user.id,
    status: { $ne: "deleted" },
  })
    .populate(
      "guide_id",
      "title category difficulty estimatedTime description steps"
    )
    .populate("template_id");

  if (!notebook) {
    return res
      .status(404)
      .json({ success: false, message: "Notebook not found" });
  }

  // Thêm stage_completion % vào response (now async)
  const notebookData = notebook.toObject();
  notebookData.stage_completion = await notebook.getCurrentStageCompletion();

  return ok(res, notebookData, null, "Fetched notebook detail successfully");
});

// 📝 Tạo mới notebook
export const createNotebook = asyncHandler(async (req, res) => {
  const { notebook_name, guide_id, description, cover_image, planted_date } =
    req.body;

  let plant_type = req.body.plant_type;
  let plant_group = null;
  let autoFoundTemplate = null;

  // ✅ FLOW TỰ ĐỘNG: Guide → plant_group → Template
  if (guide_id) {
    const guide = await Guide.findById(guide_id);
    if (!guide) {
      return res
        .status(404)
        .json({ success: false, message: "Guide not found" });
    }

    // Lấy plant_name và plant_group từ Guide
    plant_type = guide.plant_name || guide.title;
    plant_group = guide.plant_group;

    console.log(`📗 Guide found: ${guide.plant_name} → Group: ${plant_group}`);

    // Tự động tìm template dựa trên plant_group
    if (plant_group && plant_group !== "other") {
      autoFoundTemplate = await PlantTemplate.findOne({
        plant_group: plant_group,
        status: "active",
      }).sort({ usage_count: -1 }); // Lấy template được dùng nhiều nhất

      if (autoFoundTemplate) {
        console.log(
          `✅ Auto-found template: ${autoFoundTemplate.template_name}`
        );
      } else {
        console.log(`⚠️ No active template found for group: ${plant_group}`);
      }
    }
  }

  if (!plant_type) {
    return res.status(400).json({
      success: false,
      message:
        "plant_type is required. Provide either guide_id or plant_type directly.",
    });
  }

  // Tạo notebook với plant_group
  const newNotebook = await Notebook.create({
    user_id: req.user.id,
    notebook_name,
    guide_id: guide_id || undefined,
    plant_type,
    plant_group: plant_group || "other",
    description,
    cover_image,
    planted_date: planted_date || new Date(),
  });

  // ✅ TỰ ĐỘNG GÁN TEMPLATE nếu tìm được
  if (autoFoundTemplate) {
    try {
      const notebookWithTemplate = await assignTemplateToNotebook(
        newNotebook._id,
        autoFoundTemplate._id
      );

      console.log(
        `🎉 Template assigned successfully to notebook ${newNotebook._id}`
      );

      return created(
        res,
        notebookWithTemplate,
        `Notebook created with template: ${autoFoundTemplate.template_name}`
      );
    } catch (error) {
      console.error("❌ Error assigning template:", error);
      // Vẫn trả về notebook đã tạo, chỉ không có template
      return created(
        res,
        newNotebook,
        "Notebook created but template assignment failed"
      );
    }
  }

  // Không tìm được template → trả về notebook thường
  return created(
    res,
    newNotebook,
    "Notebook created successfully (no template found)"
  );
});

// 🔄 Cập nhật notebook
export const updateNotebook = asyncHandler(async (req, res) => {
  const { id } = req.params;
  const notebook = await Notebook.findOneAndUpdate(
    { _id: id, user_id: req.user.id },
    req.body,
    { new: true }
  );

  if (!notebook) {
    return res
      .status(404)
      .json({ success: false, message: "Notebook not found" });
  }

  return ok(res, notebook, null, "Notebook updated successfully");
});

// 🗑️ Xóa mềm notebook (soft delete - đánh dấu deleted)
export const deleteNotebook = asyncHandler(async (req, res) => {
  const { id } = req.params;
  const notebook = await Notebook.findOneAndUpdate(
    { _id: id, user_id: req.user.id },
    { status: "deleted", deletedAt: new Date() },
    { new: true }
  );

  if (!notebook) {
    return res
      .status(404)
      .json({ success: false, message: "Notebook not found" });
  }

  return ok(
    res,
    { id: notebook._id, status: notebook.status },
    null,
    "Notebook deleted successfully"
  );
});

// ♻️ Khôi phục notebook đã xóa
export const restoreNotebook = asyncHandler(async (req, res) => {
  const { id } = req.params;
  const notebook = await Notebook.findOneAndUpdate(
    { _id: id, user_id: req.user.id, status: "deleted" },
    { status: "active", $unset: { deletedAt: "" } },
    { new: true }
  );

  if (!notebook) {
    return res
      .status(404)
      .json({ success: false, message: "Notebook not found or not deleted" });
  }

  return ok(
    res,
    { id: notebook._id, status: notebook.status },
    null,
    "Notebook restored successfully"
  );
});

// 🗑️ Lấy danh sách notebook đã xóa
export const getDeletedNotebooks = asyncHandler(async (req, res) => {
  const notebooks = await Notebook.find({
    user_id: req.user.id,
    status: "deleted",
  })
    .populate("guide_id", "title category")
    .populate("template_id", "template_name plant_group")
    .sort({ deletedAt: -1 });

  return ok(
    res,
    notebooks,
    { count: notebooks.length },
    "Deleted notebooks fetched successfully"
  );
});

// 💀 Xóa vĩnh viễn notebook (hard delete)
export const permanentDeleteNotebook = asyncHandler(async (req, res) => {
  const { id } = req.params;

  const notebook = await Notebook.findOneAndDelete({
    _id: id,
    user_id: req.user.id,
    status: "deleted", // Chỉ cho phép xóa vĩnh viễn notebook đã ở trạng thái deleted
  });

  if (!notebook) {
    return res.status(404).json({
      success: false,
      message: "Notebook not found or not in deleted status",
    });
  }

  return ok(res, { id: notebook._id }, null, "Notebook permanently deleted");
});

// 🔍 Tìm kiếm notebook theo từ khóa
export const searchNotebooks = asyncHandler(async (req, res) => {
  const { keyword } = req.query;

  if (!keyword) {
    return res
      .status(400)
      .json({ success: false, message: "Keyword is required" });
  }

  const notebooks = await Notebook.find({
    user_id: req.user.id,
    status: { $ne: "deleted" },
    $or: [
      { notebook_name: { $regex: keyword, $options: "i" } },
      { plant_type: { $regex: keyword, $options: "i" } },
      { description: { $regex: keyword, $options: "i" } },
    ],
  })
    .populate("guide_id", "title category difficulty")
    .populate("template_id", "template_name plant_group")
    .sort({ createdAt: -1 });

  const meta = { count: notebooks.length, keyword };
  return ok(res, notebooks, meta, "Search results fetched successfully");
});

// 🧩 Lọc notebook theo tiêu chí
export const filterNotebooks = asyncHandler(async (req, res) => {
  const { plant_type, status, min_progress, max_progress, sort_by, order } =
    req.query;

  const filter = {
    user_id: req.user.id,
    status: { $ne: "deleted" },
  };

  if (plant_type) filter.plant_type = { $regex: plant_type, $options: "i" };
  if (status && ["active", "archived"].includes(status)) filter.status = status;
  if (min_progress !== undefined || max_progress !== undefined) {
    filter.progress = {};
    if (min_progress !== undefined)
      filter.progress.$gte = parseInt(min_progress);
    if (max_progress !== undefined)
      filter.progress.$lte = parseInt(max_progress);
  }

  let sortOption = { createdAt: -1 };
  if (sort_by) {
    const sortOrder = order === "asc" ? 1 : -1;
    switch (sort_by) {
      case "name":
        sortOption = { notebook_name: sortOrder };
        break;
      case "progress":
        sortOption = { progress: sortOrder };
        break;
      case "created":
        sortOption = { createdAt: sortOrder };
        break;
      case "updated":
        sortOption = { updatedAt: sortOrder };
        break;
    }
  }

  const notebooks = await Notebook.find(filter)
    .populate("guide_id", "title category difficulty estimatedTime")
    .populate("template_id", "template_name plant_group status")
    .sort(sortOption);

  const meta = {
    count: notebooks.length,
    filter: {
      plant_type: plant_type || "all",
      status: status || "all except deleted",
      progress_range: { min: min_progress || 0, max: max_progress || 100 },
      sort_by: sort_by || "created",
      order: order || "desc",
    },
  };

  return ok(res, notebooks, meta, "Filtered notebooks fetched successfully");
});

// 🖼️ Thêm ảnh vào notebook
export const addImage = asyncHandler(async (req, res) => {
  const { id } = req.params;
  const { image_url } = req.body;

  if (!image_url) {
    return res
      .status(400)
      .json({ success: false, message: "image_url is required" });
  }

  const notebook = await Notebook.findOne({
    _id: id,
    user_id: req.user.id,
    status: { $ne: "deleted" },
  });

  if (!notebook) {
    return res
      .status(404)
      .json({ success: false, message: "Notebook not found" });
  }

  notebook.images.push(image_url);
  await notebook.save();

  return ok(
    res,
    { images: notebook.images, total: notebook.images.length },
    null,
    "Image added successfully"
  );
});

// 🧹 Xóa ảnh khỏi notebook
export const removeImage = asyncHandler(async (req, res) => {
  const { id } = req.params;
  const { image_url } = req.body;

  if (!image_url) {
    return res
      .status(400)
      .json({ success: false, message: "image_url is required" });
  }

  const notebook = await Notebook.findOne({
    _id: id,
    user_id: req.user.id,
    status: { $ne: "deleted" },
  });

  if (!notebook) {
    return res
      .status(404)
      .json({ success: false, message: "Notebook not found" });
  }

  notebook.images = notebook.images.filter((img) => img !== image_url);
  await notebook.save();

  return ok(
    res,
    { images: notebook.images, total: notebook.images.length },
    null,
    "Image removed successfully"
  );
});

// 🌱 Lấy template phù hợp cho notebook
export const getNotebookTemplate = asyncHandler(async (req, res) => {
  const { id } = req.params;

  const template = await getTemplateForNotebook(id);

  if (!template) {
    return res
      .status(404)
      .json({ success: false, message: "No suitable template found" });
  }

  return ok(res, template, null, "Template fetched successfully");
});

// 📌 Gán template cho notebook
export const assignTemplate = asyncHandler(async (req, res) => {
  const { id } = req.params;
  const { template_id } = req.body;

  if (!template_id) {
    return res
      .status(400)
      .json({ success: false, message: "template_id is required" });
  }

  const notebook = await assignTemplateToNotebook(id, template_id);

  return ok(res, notebook, null, "Template assigned successfully");
});

// 📊 Lấy timeline của notebook
export const getNotebookTimeline = asyncHandler(async (req, res) => {
  const { id } = req.params;

  // Validate ID
  if (!id || id === "undefined" || id === "null") {
    return res.status(400).json({
      success: false,
      message: "Invalid notebook ID",
    });
  }

  const notebook = await Notebook.findById(id).populate("template_id");

  if (!notebook || !notebook.template_id) {
    return ok(
      res,
      null,
      { hasTemplate: false },
      "Notebook chưa có template. Vui lòng gán template để xem timeline."
    );
  }

  const template = notebook.template_id;

  const timeline = notebook.stages_tracking.map((tracking) => {
    const templateStage = template.stages.find(
      (s) => s.stage_number === tracking.stage_number
    );

    return {
      stage_number: tracking.stage_number,
      stage_name: tracking.stage_name,
      started_at: tracking.started_at,
      completed_at: tracking.completed_at,
      is_current: tracking.is_current,
      duration_days: templateStage
        ? templateStage.day_end - templateStage.day_start + 1
        : null,
      start_day: templateStage ? templateStage.day_start : null,
      end_day: templateStage ? templateStage.day_end : null,
      observations: tracking.observations,
    };
  });

  const timelineData = {
    planted_date: notebook.planted_date,
    current_day: notebook.current_day,
    progress: notebook.progress,
    total_days: template.total_days,
    timeline,
  };

  return ok(res, timelineData, null, "Timeline fetched successfully");
});

// ✅ Lấy daily checklist
export const getDailyChecklist = asyncHandler(async (req, res) => {
  const { id } = req.params;

  // Validate ID
  if (!id || id === "undefined" || id === "null") {
    return res.status(400).json({
      success: false,
      message: "Invalid notebook ID",
    });
  }

  const checklist = await generateDailyChecklist(id);

  // ✅ Return 200 with empty array instead of 404 for better UX
  if (!checklist) {
    return ok(
      res,
      [],
      { hasTemplate: false },
      "Notebook chưa có template. Vui lòng gán template để tạo checklist."
    );
  }

  return ok(res, checklist, null, "Daily checklist fetched successfully");
});

// ✔️ Đánh dấu hoàn thành task
export const completeTask = asyncHandler(async (req, res) => {
  const { id } = req.params;
  const { task_name } = req.body;

  if (!task_name) {
    return res
      .status(400)
      .json({ success: false, message: "task_name is required" });
  }

  const notebook = await completeChecklistTask(id, task_name);

  return ok(res, notebook.daily_checklist, null, "Task completed successfully");
});

// 🔄 Cập nhật stage hiện tại
export const updateStage = asyncHandler(async (req, res) => {
  const { id } = req.params;
  const { stage_number } = req.body;

  if (!stage_number) {
    return res
      .status(400)
      .json({ success: false, message: "stage_number is required" });
  }

  const notebook = await updateCurrentStage(id, stage_number);

  return ok(res, notebook, null, "Stage updated successfully");
});

// 👁️ Lấy observations của stage hiện tại
export const getCurrentObservations = asyncHandler(async (req, res) => {
  const { id } = req.params;

  const observations = await getCurrentStageObservations(id);

  return ok(
    res,
    observations,
    null,
    "Current stage observations fetched successfully"
  );
});

// 📝 Cập nhật observation
export const updateObservation = asyncHandler(async (req, res) => {
  const { id } = req.params;
  const { observation_key, value } = req.body;

  if (!observation_key || value === undefined) {
    return res.status(400).json({
      success: false,
      message: "observation_key and value are required",
    });
  }

  const notebook = await updateStageObservation(id, observation_key, value);

  // Kiểm tra xem có chuyển stage không
  const currentStage = notebook.stages_tracking.find((s) => s.is_current);
  const previousStageNumber = req.body._previousStage || notebook.current_stage;

  if (currentStage && currentStage.stage_number > previousStageNumber) {
    return ok(
      res,
      notebook,
      {
        auto_transitioned: true,
        new_stage: currentStage.stage_number,
        stage_name: currentStage.stage_name,
      },
      `✅ Đã hoàn thành tất cả điều kiện quan sát! Tự động chuyển sang ${currentStage.stage_name}.`
    );
  }

  return ok(res, notebook, null, "Observation updated successfully");
});

// 🔍 Tính stage hiện tại dựa trên số ngày
export const calculateStage = asyncHandler(async (req, res) => {
  const { id } = req.params;

  const stageInfo = await calculateCurrentStage(id);

  if (!stageInfo) {
    return res
      .status(404)
      .json({ success: false, message: "Cannot calculate stage" });
  }

  return ok(res, stageInfo, null, "Stage calculated successfully");
});

// 🔄 Recalculate progress (debug endpoint)
export const recalculateProgress = asyncHandler(async (req, res) => {
  const { id } = req.params;

  const notebook = await Notebook.findOne({
    _id: id,
    user_id: req.user.id,
  }).populate("template_id");

  if (!notebook || !notebook.template_id) {
    return res.status(404).json({
      success: false,
      message: "Notebook not found or no template assigned",
    });
  }

  // Recalculate progress
  await notebook.updateProgress(notebook.template_id.stages);
  await notebook.save();

  const stageCompletion = await notebook.getCurrentStageCompletion();

  return ok(
    res,
    {
      progress: notebook.progress,
      stage_completion: stageCompletion,
      template_stages: notebook.template_id.stages.map((s) => ({
        stage_number: s.stage_number,
        name: s.name,
        weight:
          s.weight || Math.round(100 / notebook.template_id.stages.length),
      })),
      stages_tracking: notebook.stages_tracking.map((s) => ({
        stage_number: s.stage_number,
        stage_name: s.stage_name,
        is_current: s.is_current,
        completed: !!s.completed_at,
      })),
    },
    null,
    "Progress recalculated successfully"
  );
});

// 🔧 Migrate old notebooks to add completed_tasks field
export const migrateNotebooks = asyncHandler(async (req, res) => {
  const notebooks = await Notebook.find({
    user_id: req.user.id,
  }).populate("template_id");

  let migratedCount = 0;

  for (const notebook of notebooks) {
    let needsSave = false;

    // Check each stage_tracking
    for (const stageTracking of notebook.stages_tracking) {
      // If no completed_tasks, initialize empty array
      if (!stageTracking.completed_tasks) {
        stageTracking.completed_tasks = [];
        needsSave = true;
      }
    }

    if (needsSave) {
      await notebook.save();
      migratedCount++;
      console.log(
        `✅ Migrated notebook: ${notebook.notebook_name} (${notebook._id})`
      );
    }
  }

  return ok(
    res,
    {
      total: notebooks.length,
      migrated: migratedCount,
      already_updated: notebooks.length - migratedCount,
    },
    null,
    `Migration complete! ${migratedCount} notebook(s) updated`
  );
});

// ==========================================
// STAGE MONITORING EXPORTS
// ==========================================

// 🔍 Kiểm tra một notebook cụ thể (manual trigger)
export const checkSingleNotebook = asyncHandler(async (req, res) => {
  const { id } = req.params;

  const notebook = await Notebook.findById(id).populate("template_id");

  if (!notebook) {
    return res.status(404).json({
      success: false,
      message: "Không tìm thấy notebook",
    });
  }

  await checkNotebookStageStatus(notebook);

  return ok(
    res,
    {
      notebook_id: notebook._id,
      notebook_name: notebook.notebook_name,
      current_stage: notebook.current_stage,
      stages_tracking: notebook.stages_tracking.map((s) => ({
        stage_number: s.stage_number,
        stage_name: s.stage_name,
        status: s.status,
        missed_days: s.missed_days,
        is_current: s.is_current,
      })),
    },
    null,
    "Notebook stage status checked successfully"
  );
});

// 🔄 Monitor tất cả notebooks (admin/cron endpoint)
export const monitorAllNotebooks = asyncHandler(async (req, res) => {
  console.log("🔍 Bắt đầu monitor tất cả notebooks...");

  try {
    const notebooks = await Notebook.find({
      status: "active",
      template_id: { $exists: true, $ne: null },
    }).populate("template_id");

    console.log(`📊 Tìm thấy ${notebooks.length} notebooks cần kiểm tra`);

    for (const notebook of notebooks) {
      await checkNotebookStageStatus(notebook);
    }

    console.log("✅ Hoàn thành monitor tất cả notebooks");

    return ok(
      res,
      {
        total_checked: notebooks.length,
        timestamp: new Date(),
      },
      null,
      "All notebooks monitored successfully"
    );
  } catch (error) {
    console.error("❌ Lỗi khi monitor notebooks:", error);
    return res.status(500).json({
      success: false,
      message: "Error monitoring notebooks",
      error: error.message,
    });
  }
});

// ==========================================
// DAILY STATUS & OVERDUE MANAGEMENT
// ==========================================

// 📅 Lấy trạng thái hàng ngày (tasks hôm nay + overdue summary)
export const getDailyStatus = asyncHandler(async (req, res) => {
  const { id } = req.params; // notebook_id

  const notebook = await Notebook.findOne({
    _id: id,
    user_id: req.user.id,
    status: { $ne: "deleted" },
  }).populate("template_id");

  if (!notebook) {
    return res.status(404).json({
      success: false,
      message: "Notebook not found",
    });
  }

  console.log(
    `🔔 getDailyStatus called for notebook=${id} user=${req.user?.id}`
  );

  // Tạo checklist cho hôm nay (sẽ tự động xử lý overdue nếu sang ngày mới)
  await generateDailyChecklist(id);

  // Reload notebook sau khi generate
  const updatedNotebook = await Notebook.findById(id).populate("template_id");

  const currentStageTracking = updatedNotebook.stages_tracking.find(
    (s) => s.stage_number === updatedNotebook.current_stage
  );

  const today = getVietnamToday();
  const overdueSummary = currentStageTracking?.overdue_summary?.ready_to_notify
    ? {
        overdue_date: currentStageTracking.overdue_summary.date,
        overdue_count: currentStageTracking.overdue_summary.overdue_count,
      }
    : null;

  return ok(
    res,
    {
      today: today.toISOString().split("T")[0],
      current_day: updatedNotebook.current_day,
      tasks_today: updatedNotebook.daily_checklist,
      overdue_summary: overdueSummary,
    },
    null,
    "Daily status fetched successfully"
  );
});

// 🗑️ Bỏ qua tất cả overdue tasks
export const skipOverdueTasks = asyncHandler(async (req, res) => {
  const { id } = req.params; // notebook_id

  const notebook = await Notebook.findOne({
    _id: id,
    user_id: req.user.id,
    status: { $ne: "deleted" },
  });

  if (!notebook) {
    return res.status(404).json({
      success: false,
      message: "Notebook not found",
    });
  }

  // Đánh dấu tất cả overdue tasks (được lưu trong stageTracking.overdue_tasks) = skipped
  const currentStageTracking = notebook.stages_tracking.find(
    (s) => s.stage_number === notebook.current_stage
  );

  if (!currentStageTracking || !currentStageTracking.overdue_tasks) {
    return ok(res, null, null, "No overdue tasks to skip");
  }

  const overdueTasks = currentStageTracking.overdue_tasks.filter(
    (t) => t.status === "overdue"
  );

  if (overdueTasks.length === 0) {
    return ok(res, null, null, "No overdue tasks to skip");
  }

  overdueTasks.forEach((t) => {
    t.status = "skipped";
    t.skipped_at = new Date();
  });

  // Reset overdue_summary notify flag
  if (currentStageTracking && currentStageTracking.overdue_summary) {
    currentStageTracking.overdue_summary.ready_to_notify = false;
    currentStageTracking.overdue_summary.notified_at = new Date();
  }

  await notebook.save();

  return ok(
    res,
    { skipped_count: overdueTasks.length },
    null,
    `${overdueTasks.length} overdue tasks skipped successfully`
  );
});

// ✅ Hoàn thành một overdue task (hoàn thành bù)
export const completeOverdueTask = asyncHandler(async (req, res) => {
  const { id } = req.params; // notebook_id
  const { task_name } = req.body;

  if (!task_name) {
    return res
      .status(400)
      .json({ success: false, message: "task_name is required" });
  }

  const notebook = await Notebook.findOne({
    _id: id,
    user_id: req.user.id,
    status: { $ne: "deleted" },
  }).populate("template_id");

  if (!notebook) {
    return res
      .status(404)
      .json({ success: false, message: "Notebook not found" });
  }

  const currentStageTracking = notebook.stages_tracking.find(
    (s) => s.stage_number === notebook.current_stage
  );

  if (!currentStageTracking || !currentStageTracking.overdue_tasks) {
    return res
      .status(404)
      .json({ success: false, message: "No overdue tasks found" });
  }

  const task = currentStageTracking.overdue_tasks.find(
    (t) => t.task_name === task_name && t.status === "overdue"
  );

  if (!task) {
    return res
      .status(404)
      .json({ success: false, message: "Overdue task not found" });
  }

  // Mark as completed
  task.is_completed = true;
  task.completed_at = new Date();
  task.status = "completed";

  // Add to completed_tasks for tracking (if not already)
  if (!currentStageTracking.completed_tasks) {
    currentStageTracking.completed_tasks = [];
  }
  const alreadyCompleted = currentStageTracking.completed_tasks.some(
    (t) => t.task_name === task_name
  );
  if (!alreadyCompleted) {
    currentStageTracking.completed_tasks.push({
      task_name,
      completed_at: new Date(),
    });
  }

  // Update today's daily_log progress to include this makeup completion
  const todayDate = getVietnamToday();
  const today = todayDate.toISOString().split("T")[0];

  if (!currentStageTracking.daily_logs) {
    currentStageTracking.daily_logs = [];
  }

  let dailyLog = currentStageTracking.daily_logs.find(
    (log) => log.date?.toISOString().split("T")[0] === today
  );

  if (!dailyLog) {
    dailyLog = { date: todayDate, daily_progress: 0 };
    currentStageTracking.daily_logs.push(dailyLog);
  }

  // Compute new daily progress: existing completed today + this makeup / total today tasks
  const todayTasks = notebook.daily_checklist || [];
  const completedTodayTasks = todayTasks.filter((t) => t.is_completed).length;
  const totalTodayTasks = todayTasks.length || 0;

  if (totalTodayTasks > 0) {
    const newProgress = Math.min(
      100,
      Math.round(((completedTodayTasks + 1) / totalTodayTasks) * 100)
    );
    dailyLog.daily_progress = newProgress;
  } else {
    // If no daily tasks today, conservatively set a small progress increment (e.g., 10%)
    dailyLog.daily_progress = Math.min(
      100,
      (dailyLog.daily_progress || 0) + 10
    );
  }

  // Recalculate overall progress
  if (notebook.template_id && notebook.template_id.stages) {
    await notebook.updateProgress(notebook.template_id.stages);
    console.log(
      `📊 Progress updated after completing overdue task: ${notebook.progress}%`
    );
  }
  // Recompute overdue_summary count and notify flag
  const remainingOverdue = currentStageTracking.overdue_tasks.filter(
    (t) => t.status === "overdue"
  ).length;

  if (!currentStageTracking.overdue_summary) {
    currentStageTracking.overdue_summary = {
      date: null,
      overdue_count: 0,
      ready_to_notify: false,
    };
  }

  currentStageTracking.overdue_summary.overdue_count = remainingOverdue;
  if (remainingOverdue === 0) {
    currentStageTracking.overdue_summary.ready_to_notify = false;
    currentStageTracking.overdue_summary.notified_at = new Date();
  }

  await notebook.save();

  return ok(
    res,
    {
      notebook_id: notebook._id,
      stage_completion: notebook.stage_completion,
      progress: notebook.progress,
    },
    null,
    "Overdue task completed successfully"
  );
});

// 📋 Lấy chi tiết overdue tasks
export const getOverdueDetail = asyncHandler(async (req, res) => {
  const { id } = req.params; // notebook_id

  const notebook = await Notebook.findOne({
    _id: id,
    user_id: req.user.id,
    status: { $ne: "deleted" },
  });

  if (!notebook) {
    return res.status(404).json({
      success: false,
      message: "Notebook not found",
    });
  }

  console.log(
    `🔔 getOverdueDetail called for notebook=${id} user=${req.user?.id}`
  );

  const currentStageTracking = notebook.stages_tracking.find(
    (s) => s.stage_number === notebook.current_stage
  );

  const overdueTasks = currentStageTracking?.overdue_tasks || [];

  console.log(
    `🔍 Overdue tasks for notebook=${id} stage=${notebook.current_stage}: persisted=${overdueTasks.length}`
  );

  return ok(
    res,
    {
      overdue_date: currentStageTracking?.overdue_summary?.date || null,
      overdue_count: overdueTasks.length,
      overdue_tasks: overdueTasks,
    },
    null,
    "Overdue tasks detail fetched successfully"
  );
});

// =====================
// Notebook statistics
// =====================
export const getStats = asyncHandler(async (req, res) => {
  const userId = req.user?.id;

  const match = { status: { $ne: "deleted" } };
  if (userId) match.user_id = new mongoose.Types.ObjectId(userId);

  // By type
  const byTypeAgg = await Notebook.aggregate([
    { $match: match },
    { $group: { _id: "$plant_type", count: { $sum: 1 } } },
    { $sort: { count: -1 } },
  ]);

  // By group
  const byGroupAgg = await Notebook.aggregate([
    { $match: match },
    { $group: { _id: "$plant_group", count: { $sum: 1 } } },
    { $sort: { count: -1 } },
  ]);

  // Average progress
  const progressAgg = await Notebook.aggregate([
    { $match: match },
    { $group: { _id: null, avgProgress: { $avg: "$progress" } } },
  ]);

  const avgProgress = progressAgg[0]?.avgProgress ?? 0;

  // Progress distribution
  const distributionAgg = await Notebook.aggregate([
    { $match: match },
    {
      $bucket: {
        groupBy: "$progress",
        boundaries: [0, 25, 50, 75, 100, 101],
        default: "unknown",
        output: { count: { $sum: 1 } },
      },
    },
  ]);

  const progressDistribution = {
    "0-25": 0,
    "25-50": 0,
    "50-75": 0,
    "75-100": 0,
  };
  distributionAgg.forEach((b) => {
    const key = b._id;
    if (key === 0) progressDistribution["0-25"] = b.count;
    else if (key === 25) progressDistribution["25-50"] = b.count;
    else if (key === 50) progressDistribution["50-75"] = b.count;
    else if (key === 75) progressDistribution["75-100"] = b.count;
  });

  // Most popular type
  const mostPopularType = byTypeAgg.length > 0 ? byTypeAgg[0]._id : null;

  // Average grow days (planted_date -> max completed_at)
  const avgGrowAgg = await Notebook.aggregate([
    { $match: match },
    {
      $addFields: { maxCompletedAt: { $max: "$stages_tracking.completed_at" } },
    },
    {
      $match: {
        planted_date: { $exists: true, $ne: null },
        maxCompletedAt: { $exists: true, $ne: null },
      },
    },
    {
      $project: {
        diffDays: {
          $divide: [
            { $subtract: ["$maxCompletedAt", "$planted_date"] },
            1000 * 60 * 60 * 24,
          ],
        },
      },
    },
    { $group: { _id: null, avgGrowDays: { $avg: "$diffDays" } } },
  ]);

  const avgGrowDays = avgGrowAgg[0]?.avgGrowDays ?? null;

  const byType = {};
  byTypeAgg.forEach((r) => (byType[r._id || "Unknown"] = r.count));

  const byGroup = {};
  byGroupAgg.forEach((r) => (byGroup[r._id || "unknown"] = r.count));

  const result = {
    byType,
    byGroup,
    mostPopularType,
    progressAvg: Math.round(avgProgress),
    progressDistribution,
    avgGrowDays: avgGrowDays ? Math.round(avgGrowDays) : null,
  };

  return ok(res, result, null, "Notebook statistics fetched successfully");
});
