import dotenv from "dotenv";
import path from "path";
import { fileURLToPath } from "url";
import mongoose from "mongoose";
import PlantTemplate from "../models/PlantTemplate.js";
import Notebook from "../models/Notebook.js";

// Load env from backend/.env
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
dotenv.config({ path: path.resolve(__dirname, "..", ".env") });

const MONGO = process.env.MONGODB_CONNECTIONSTRING || process.env.MONGO_URI;

if (!MONGO) {
  console.error(
    "Missing MongoDB connection string. Set MONGODB_CONNECTIONSTRING in .env"
  );
  process.exit(1);
}

const connect = async () => {
  try {
    console.log("Connecting to MongoDB...");
    await mongoose.connect(MONGO, { autoIndex: false });
    console.log("MongoDB connection established");
  } catch (err) {
    console.error("Failed to connect to MongoDB:", err.message || err);
    throw err;
  }
};

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

/**
 * Test overdue flow:
 * 1. Tạo notebook với checklist ngày hôm qua
 * 2. Gọi generateDailyChecklist → trigger overdue marking
 * 3. Kiểm tra overdue_summary và task status
 */
const run = async () => {
  await connect();
  console.log("🧪 Starting overdue flow test...\n");

  // Tạo template test
  const tplName = `TEST_OVERDUE_TEMPLATE_${Date.now()}`;

  const stages = [
    {
      stage_number: 1,
      name: "Test Stage 1",
      day_start: 1,
      day_end: 10,
      autogenerated_tasks: [
        {
          task_name: "Tưới nước",
          description: "Tưới nước 2 lần/ngày",
          frequency: "daily",
          priority: "high",
        },
        {
          task_name: "Kiểm tra sâu bệnh",
          description: "Kiểm tra lá và thân cây",
          frequency: "daily",
          priority: "medium",
        },
      ],
    },
    {
      stage_number: 2,
      name: "Test Stage 2",
      day_start: 11,
      day_end: 20,
    },
    {
      stage_number: 3,
      name: "Test Stage 3",
      day_start: 21,
      day_end: 30,
    },
  ];

  const template = await PlantTemplate.create({
    template_name: tplName,
    plant_group: "other",
    status: "active",
    stages,
    created_by: new mongoose.Types.ObjectId(),
  });

  console.log(`✅ Created template: ${template._id}\n`);

  // Tạo notebook với planted_date = 2 ngày trước (current_day = 2)
  const plantedDate = new Date();
  plantedDate.setDate(plantedDate.getDate() - 2);

  // Tạo ngày hôm qua để set last_checklist_generated
  const yesterday = new Date();
  yesterday.setDate(yesterday.getDate() - 1);
  yesterday.setHours(0, 0, 0, 0);

  const notebook = await Notebook.create({
    user_id: new mongoose.Types.ObjectId(),
    template_id: template._id,
    notebook_name: `TEST_OVERDUE_NOTE_${Date.now()}`,
    plant_type: "test",
    plant_group: "other",
    planted_date: plantedDate,
    current_stage: 1,
    stages_tracking: [
      {
        stage_number: 1,
        stage_name: "Test Stage 1",
        started_at: plantedDate,
        is_current: true,
        status: "active",
      },
    ],
    // Giả lập đã tạo checklist hôm qua
    last_checklist_generated: yesterday,
    daily_checklist: [
      {
        task_name: "Tưới nước",
        description: "Tưới nước 2 lần/ngày",
        priority: "high",
        frequency: "daily",
        is_completed: false,
        status: "pending",
      },
      {
        task_name: "Kiểm tra sâu bệnh",
        description: "Kiểm tra lá và thân cây",
        priority: "medium",
        frequency: "daily",
        is_completed: false,
        status: "pending",
      },
    ],
  });

  console.log(`✅ Created notebook: ${notebook._id}`);
  console.log(`📅 Planted date: ${plantedDate.toISOString().split("T")[0]}`);
  console.log(
    `📅 Last checklist generated: ${yesterday.toISOString().split("T")[0]}`
  );
  console.log(`📊 Current day: ${notebook.current_day}`);
  console.log(
    `📋 Daily checklist (yesterday): ${notebook.daily_checklist.length} tasks\n`
  );

  // Import generateDailyChecklist function (giống controller)
  const { getDaysDifferenceVN, toVietnamMidnight, getVietnamToday } =
    await import("../utils/timezone.js");

  const generateDailyChecklist = async (notebookId) => {
    const nb = await Notebook.findById(notebookId).populate("template_id");

    if (!nb || !nb.template_id) {
      return null;
    }

    const tmpl = nb.template_id;
    const currentStage = tmpl.stages.find(
      (s) => s.stage_number === nb.current_stage
    );

    if (!currentStage) {
      return null;
    }

    const today = getVietnamToday();
    const currentDay = nb.current_day || 1;

    if (currentDay < currentStage.day_start) {
      nb.daily_checklist = [];
      nb.last_checklist_generated = today;
      await nb.save();
      return [];
    }

    const lastGenerated = nb.last_checklist_generated
      ? toVietnamMidnight(nb.last_checklist_generated)
      : null;

    if (lastGenerated && lastGenerated.getTime() === today.getTime()) {
      return nb.daily_checklist;
    }

    // ✅ SANG NGÀY MỚI → Xử lý overdue
    if (lastGenerated && lastGenerated.getTime() < today.getTime()) {
      const currentStageTracking = nb.stages_tracking.find(
        (s) => s.stage_number === nb.current_stage
      );

      if (currentStageTracking) {
        const incompleteTasks = nb.daily_checklist.filter(
          (task) => !task.is_completed && task.status === "pending"
        );

        if (incompleteTasks.length > 0) {
          console.log(
            `⚠️  Đánh dấu ${incompleteTasks.length} tasks của ngày ${
              lastGenerated.toISOString().split("T")[0]
            } = overdue`
          );

          incompleteTasks.forEach((task) => {
            task.status = "overdue";
            task.overdue_at = today;
          });

          currentStageTracking.overdue_summary = {
            date: lastGenerated,
            overdue_count: incompleteTasks.length,
            ready_to_notify: true,
          };

          console.log(
            `📊 Overdue summary saved: ${incompleteTasks.length} tasks\n`
          );
        }
      }
    }

    // Tạo checklist mới cho hôm nay
    const daysInStage = Math.floor(nb.current_day) - currentStage.day_start + 1;

    const newChecklist = (currentStage.autogenerated_tasks || []).map(
      (task) => ({
        task_name: task.task_name,
        description: task.description,
        priority: task.priority,
        frequency: task.frequency,
        is_completed: false,
        status: "pending",
      })
    );

    nb.daily_checklist = newChecklist;
    nb.last_checklist_generated = today;
    await nb.save();

    return newChecklist;
  };

  // Gọi generateDailyChecklist
  console.log(
    "🔄 Calling generateDailyChecklist (trigger overdue marking)...\n"
  );
  await generateDailyChecklist(notebook._id);

  // Reload notebook để kiểm tra kết quả
  const updatedNotebook = await Notebook.findById(notebook._id);

  console.log("📊 RESULTS:");
  console.log("=".repeat(50));
  console.log(`Today: ${getVietnamToday().toISOString().split("T")[0]}`);
  console.log(`Current day: ${updatedNotebook.current_day}`);
  console.log(
    `Last checklist generated: ${
      updatedNotebook.last_checklist_generated.toISOString().split("T")[0]
    }`
  );
  console.log(
    `\nDaily checklist (today): ${updatedNotebook.daily_checklist.length} tasks`
  );

  updatedNotebook.daily_checklist.forEach((task, idx) => {
    console.log(
      `  ${idx + 1}. ${task.task_name} - Status: ${task.status}${
        task.overdue_at
          ? ` (overdue_at: ${task.overdue_at.toISOString().split("T")[0]})`
          : ""
      }`
    );
  });

  const currentStageTracking = updatedNotebook.stages_tracking.find(
    (s) => s.stage_number === updatedNotebook.current_stage
  );

  if (currentStageTracking?.overdue_summary) {
    console.log(`\nOverdue Summary:`);
    console.log(
      `  Date: ${
        currentStageTracking.overdue_summary.date.toISOString().split("T")[0]
      }`
    );
    console.log(
      `  Count: ${currentStageTracking.overdue_summary.overdue_count}`
    );
    console.log(
      `  Ready to notify: ${currentStageTracking.overdue_summary.ready_to_notify}`
    );
  } else {
    console.log(`\n❌ No overdue_summary found`);
  }

  console.log("=".repeat(50));

  // Cleanup
  await sleep(300);
  await Notebook.deleteMany({ notebook_name: /TEST_OVERDUE_NOTE_/ });
  await PlantTemplate.deleteOne({ _id: template._id });

  console.log("\n✅ Cleaned up test documents. Closing connection.");
  await mongoose.disconnect();
  process.exit(0);
};

run().catch((err) => {
  console.error("Error in testOverdueFlow:", err);
  mongoose.disconnect().finally(() => process.exit(1));
});
