import React, { useState, useEffect } from "react";
import { useNavigate, useParams } from "react-router-dom";
import plantTemplateApi from "../../api/expert/plantTemplateApi";
import {
  Step2Stages,
  Step3Tasks,
  Step4Observations,
  Step5Review,
} from "../../components/expert/TemplateFormSteps";
import "../../css/expert/PlantTemplateForm.css";

const PlantTemplateForm = ({ mode = "create" }) => {
  const navigate = useNavigate();
  const { id } = useParams();
  const [currentStep, setCurrentStep] = useState(1);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const [formData, setFormData] = useState({
    template_name: "",
    plant_group: "leaf_vegetable",
    group_description: "",
    plant_examples: [],
    stages: [],
    rules: {
      safe_delay_days: 3,
      auto_skip: true,
      warning_days: 1,
    },
    status: "draft",
    notes: "",
  });

  const [tempInput, setTempInput] = useState("");

  const plantGroups = [
    { value: "leaf_vegetable", label: "Rau ăn lá", icon: "🥬" },
    { value: "root_vegetable", label: "Cây củ", icon: "🥕" },
    { value: "fruit_short_term", label: "Rau/quả ngắn ngày", icon: "🥒" },
    { value: "fruit_long_term", label: "Cây ăn quả dài ngày", icon: "🍊" },
    { value: "bean_family", label: "Họ đậu", icon: "🫘" },
    { value: "herb", label: "Cây gia vị", icon: "🌿" },
    { value: "flower_vegetable", label: "Rau ăn hoa", icon: "🥦" },
    { value: "other", label: "Khác", icon: "🌱" },
  ];

  const steps = [
    { number: 1, title: "Thông tin cơ bản", icon: "📝" },
    { number: 2, title: "Giai đoạn phát triển", icon: "🌱" },
    { number: 3, title: "Nhiệm vụ tự động", icon: "✅" },
    { number: 4, title: "Điều kiện quan sát", icon: "👁️" },
    { number: 5, title: "Quy tắc & Xác nhận", icon: "⚙️" },
  ];

  useEffect(() => {
    if (mode === "edit" && id) {
      loadTemplate();
    }
  }, [mode, id]);

  const loadTemplate = async () => {
    try {
      setLoading(true);
      const response = await plantTemplateApi.getTemplateById(id);
      const template = response.data?.data?.template;
      if (template) {
        setFormData({
          template_name: template.template_name,
          plant_group: template.plant_group,
          group_description: template.group_description || "",
          plant_examples: template.plant_examples || [],
          stages: template.stages || [],
          rules: template.rules || formData.rules,
          status: template.status || "draft",
          notes: template.notes || "",
        });
      }
    } catch (err) {
      console.error("Error loading template:", err);
      setError("Không thể tải template");
    } finally {
      setLoading(false);
    }
  };

  const handleInputChange = (field, value) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
  };

  const handleRuleChange = (field, value) => {
    setFormData((prev) => ({
      ...prev,
      rules: { ...prev.rules, [field]: value },
    }));
  };

  const addPlantExample = () => {
    if (tempInput.trim()) {
      setFormData((prev) => ({
        ...prev,
        plant_examples: [...prev.plant_examples, tempInput.trim()],
      }));
      setTempInput("");
    }
  };

  const removePlantExample = (index) => {
    setFormData((prev) => ({
      ...prev,
      plant_examples: prev.plant_examples.filter((_, i) => i !== index),
    }));
  };

  const addStage = () => {
    const newStageNumber = formData.stages.length + 1;
    const lastStage = formData.stages[formData.stages.length - 1];
    const dayStart = lastStage ? lastStage.day_end + 1 : 1;

    setFormData((prev) => ({
      ...prev,
      stages: [
        ...prev.stages,
        {
          stage_number: newStageNumber,
          name: "",
          description: "",
          day_start: dayStart,
          day_end: dayStart + 6,
          stage_image: null,
          autogenerated_tasks: [],
          observation_required: [],
        },
      ],
    }));
  };

  const updateStage = (index, field, value) => {
    setFormData((prev) => ({
      ...prev,
      stages: prev.stages.map((stage, i) =>
        i === index ? { ...stage, [field]: value } : stage
      ),
    }));
  };

  const removeStage = (index) => {
    setFormData((prev) => ({
      ...prev,
      stages: prev.stages
        .filter((_, i) => i !== index)
        .map((stage, i) => ({ ...stage, stage_number: i + 1 })),
    }));
  };

  const addTaskToStage = (stageIndex) => {
    const newTask = {
      task_name: "",
      description: "",
      frequency: "daily",
      illustration_image: null,
      priority: "medium",
    };

    setFormData((prev) => ({
      ...prev,
      stages: prev.stages.map((stage, i) =>
        i === stageIndex
          ? {
              ...stage,
              autogenerated_tasks: [...stage.autogenerated_tasks, newTask],
            }
          : stage
      ),
    }));
  };

  const updateTask = (stageIndex, taskIndex, field, value) => {
    setFormData((prev) => ({
      ...prev,
      stages: prev.stages.map((stage, i) =>
        i === stageIndex
          ? {
              ...stage,
              autogenerated_tasks: stage.autogenerated_tasks.map((task, j) =>
                j === taskIndex ? { ...task, [field]: value } : task
              ),
            }
          : stage
      ),
    }));
  };

  const removeTask = (stageIndex, taskIndex) => {
    setFormData((prev) => ({
      ...prev,
      stages: prev.stages.map((stage, i) =>
        i === stageIndex
          ? {
              ...stage,
              autogenerated_tasks: stage.autogenerated_tasks.filter(
                (_, j) => j !== taskIndex
              ),
            }
          : stage
      ),
    }));
  };

  const addObservationToStage = (stageIndex) => {
    const newObservation = {
      key: "",
      label: "",
      description: "",
    };

    setFormData((prev) => ({
      ...prev,
      stages: prev.stages.map((stage, i) =>
        i === stageIndex
          ? {
              ...stage,
              observation_required: [
                ...stage.observation_required,
                newObservation,
              ],
            }
          : stage
      ),
    }));
  };

  const updateObservation = (stageIndex, obsIndex, field, value) => {
    setFormData((prev) => ({
      ...prev,
      stages: prev.stages.map((stage, i) =>
        i === stageIndex
          ? {
              ...stage,
              observation_required: stage.observation_required.map((obs, j) =>
                j === obsIndex ? { ...obs, [field]: value } : obs
              ),
            }
          : stage
      ),
    }));
  };

  const removeObservation = (stageIndex, obsIndex) => {
    setFormData((prev) => ({
      ...prev,
      stages: prev.stages.map((stage, i) =>
        i === stageIndex
          ? {
              ...stage,
              observation_required: stage.observation_required.filter(
                (_, j) => j !== obsIndex
              ),
            }
          : stage
      ),
    }));
  };

  const validateStep = (step) => {
    switch (step) {
      case 1:
        if (!formData.template_name.trim()) {
          setError("Vui lòng nhập tên template");
          return false;
        }
        if (!formData.plant_group) {
          setError("Vui lòng chọn nhóm cây");
          return false;
        }
        break;
      case 2:
        if (formData.stages.length < 3) {
          setError("Template phải có ít nhất 3 giai đoạn");
          return false;
        }
        for (let stage of formData.stages) {
          if (!stage.name.trim()) {
            setError(`Giai đoạn ${stage.stage_number} chưa có tên`);
            return false;
          }
          if (stage.day_start >= stage.day_end) {
            setError(
              `Giai đoạn ${stage.stage_number}: Ngày bắt đầu phải nhỏ hơn ngày kết thúc`
            );
            return false;
          }
        }
        break;
      case 3:
        // Tasks validation (optional)
        break;
      case 4:
        // Observations validation (optional)
        break;
    }
    setError(null);
    return true;
  };

  const nextStep = () => {
    if (validateStep(currentStep)) {
      setCurrentStep((prev) => Math.min(prev + 1, 5));
    }
  };

  const prevStep = () => {
    setCurrentStep((prev) => Math.max(prev - 1, 1));
    setError(null);
  };

  const handleSubmit = async () => {
    if (!validateStep(currentStep)) return;

    try {
      setLoading(true);

      if (mode === "edit") {
        await plantTemplateApi.updateTemplate(id, formData);
        alert("Cập nhật template thành công!");
      } else {
        await plantTemplateApi.createTemplate(formData);
        alert("Tạo template thành công!");
      }

      navigate("/expert/plant-templates");
    } catch (err) {
      console.error("Error saving template:", err);
      setError(err.response?.data?.message || "Không thể lưu template");
    } finally {
      setLoading(false);
    }
  };

  if (loading && mode === "edit") {
    return (
      <div className="plant-template-form">
        <div className="loading-container">
          <div className="spinner"></div>
          <p>Đang tải...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="plant-template-form">
      <div className="form-container">
        <div className="form-header">
          <button className="btn-back" onClick={() => navigate(-1)}>
            ← Quay lại
          </button>
          <h1>{mode === "edit" ? "Chỉnh sửa" : "Tạo mới"} Plant Template</h1>
        </div>

        {/* Steps Progress */}
        <div className="steps-progress">
          {steps.map((step) => (
            <div
              key={step.number}
              className={`step-item ${
                currentStep === step.number ? "active" : ""
              } ${currentStep > step.number ? "completed" : ""}`}
            >
              <div className="step-number">
                {currentStep > step.number ? "✓" : step.icon}
              </div>
              <div className="step-title">{step.title}</div>
            </div>
          ))}
        </div>

        {error && (
          <div className="alert alert-error">
            <span className="icon">⚠️</span>
            {error}
          </div>
        )}

        {/* Step Content */}
        <div className="step-content">
          {currentStep === 1 && (
            <Step1BasicInfo
              formData={formData}
              handleInputChange={handleInputChange}
              plantGroups={plantGroups}
              tempInput={tempInput}
              setTempInput={setTempInput}
              addPlantExample={addPlantExample}
              removePlantExample={removePlantExample}
            />
          )}

          {currentStep === 2 && (
            <Step2Stages
              stages={formData.stages}
              addStage={addStage}
              updateStage={updateStage}
              removeStage={removeStage}
            />
          )}

          {currentStep === 3 && (
            <Step3Tasks
              stages={formData.stages}
              addTaskToStage={addTaskToStage}
              updateTask={updateTask}
              removeTask={removeTask}
            />
          )}

          {currentStep === 4 && (
            <Step4Observations
              stages={formData.stages}
              addObservationToStage={addObservationToStage}
              updateObservation={updateObservation}
              removeObservation={removeObservation}
            />
          )}

          {currentStep === 5 && (
            <Step5Review
              formData={formData}
              handleRuleChange={handleRuleChange}
              handleInputChange={handleInputChange}
            />
          )}
        </div>

        {/* Navigation Buttons */}
        <div className="form-navigation">
          <button
            className="btn btn-secondary"
            onClick={prevStep}
            disabled={currentStep === 1 || loading}
          >
            ← Quay lại
          </button>

          <div className="nav-info">
            Bước {currentStep} / {steps.length}
          </div>

          {currentStep < 5 ? (
            <button className="btn btn-primary" onClick={nextStep}>
              Tiếp theo →
            </button>
          ) : (
            <button
              className="btn btn-success"
              onClick={handleSubmit}
              disabled={loading}
            >
              {loading
                ? "Đang lưu..."
                : mode === "edit"
                ? "Cập nhật"
                : "Tạo template"}
            </button>
          )}
        </div>
      </div>
    </div>
  );
};

// Step 1: Basic Info Component
const Step1BasicInfo = ({
  formData,
  handleInputChange,
  plantGroups,
  tempInput,
  setTempInput,
  addPlantExample,
  removePlantExample,
}) => (
  <div className="step-basic-info">
    <h2>Thông tin cơ bản</h2>

    <div className="form-group">
      <label>
        Tên Template <span className="required">*</span>
      </label>
      <input
        type="text"
        className="form-input"
        placeholder="Ví dụ: Rau ăn lá cơ bản"
        value={formData.template_name}
        onChange={(e) => handleInputChange("template_name", e.target.value)}
      />
    </div>

    <div className="form-group">
      <label>
        Nhóm cây <span className="required">*</span>
      </label>
      <div className="plant-groups-grid">
        {plantGroups.map((group) => (
          <div
            key={group.value}
            className={`group-card ${
              formData.plant_group === group.value ? "selected" : ""
            }`}
            onClick={() => handleInputChange("plant_group", group.value)}
          >
            <div className="group-icon">{group.icon}</div>
            <div className="group-label">{group.label}</div>
          </div>
        ))}
      </div>
    </div>

    <div className="form-group">
      <label>Mô tả nhóm cây</label>
      <textarea
        className="form-textarea"
        rows="3"
        placeholder="Mô tả về nhóm cây này..."
        value={formData.group_description}
        onChange={(e) => handleInputChange("group_description", e.target.value)}
      />
    </div>

    <div className="form-group">
      <label>Ví dụ cây thuộc nhóm</label>
      <div className="input-with-button">
        <input
          type="text"
          className="form-input"
          placeholder="Nhập tên cây, ví dụ: Xà lách"
          value={tempInput}
          onChange={(e) => setTempInput(e.target.value)}
          onKeyPress={(e) => e.key === "Enter" && addPlantExample()}
        />
        <button
          type="button"
          className="btn btn-sm btn-primary"
          onClick={addPlantExample}
        >
          Thêm
        </button>
      </div>

      {formData.plant_examples.length > 0 && (
        <div className="tags-list">
          {formData.plant_examples.map((example, index) => (
            <span key={index} className="tag">
              {example}
              <button
                type="button"
                className="tag-remove"
                onClick={() => removePlantExample(index)}
              >
                ×
              </button>
            </span>
          ))}
        </div>
      )}
    </div>
  </div>
);

// Continue with other step components in next file...
export default PlantTemplateForm;
