import mongoose from "mongoose";
import dotenv from "dotenv";
import moment from "moment-timezone";

import User from "../models/User.js";
import PlantTemplate from "../models/PlantTemplate.js";
import Notebook from "../models/Notebook.js";
import Notification from "../models/Notification.js";
import { sendDailyReminderNotification } from "../controllers/notificationController.js";
import { getVietnamToday, toVietnamMidnight } from "../utils/timezone.js";

dotenv.config();

// Accept several common env var names to be tolerant with existing .env files
const MONGODB_URI =
  process.env.MONGODB_URI ||
  process.env.MONGO_URI ||
  process.env.MONGODB_CONNECTIONSTRING ||
  process.env.MONGO_URL ||
  process.env.MONGO;
const VIETNAM_TZ = "Asia/Ho_Chi_Minh";

const log = (...args) => console.log(new Date().toISOString(), ...args);

/**
 * Test script:
 * - Create a PlantTemplate for basil (Hung Be)
 * - Create/find a test user
 * - Create a Notebook such that day-20 task was created yesterday and is incomplete
 * - Trigger a daily reminder (via sending a notification)
 * - Simulate user clicking notification and completing the overdue (day-20) task
 * - Recompute stage completion and overall progress
 * - Simulate day-21 task completion and ensure stage completion reaches 100%
 */
const main = async () => {
  if (!MONGODB_URI) {
    console.error(
      "Please set one of MONGODB_URI, MONGO_URI or MONGODB_CONNECTIONSTRING in .env before running this script"
    );
    process.exit(1);
  }

  await mongoose.connect(MONGODB_URI);
  log("Connected to MongoDB");

  // 1) Find or create test user
  let user = await User.findOne({ username: "test_overdue_user" });
  if (!user) {
    user = await User.create({
      username: "test_overdue_user",
      email: "test_overdue_user+bot@example.com",
      provider: "local",
      password: "password123",
    });
    log("Created test user", user._id.toString());
  } else {
    log("Found test user", user._id.toString());
  }

  // 2) Create a simple basil template (Hung Be) where stage 1 spans 2 days (day 20-21)
  let template = await PlantTemplate.findOne({
    template_name: "HungBe Test Template",
  });
  if (!template) {
    template = await PlantTemplate.create({
      template_name: "HungBe Test Template",
      plant_group: "herb",
      created_by: user._id,
      stages: [
        {
          stage_number: 1,
          name: "Giai doan 1 (test)",
          day_start: 20,
          day_end: 21,
          weight: 50,
          autogenerated_tasks: [
            { task_name: "Tuoi nuoc", frequency: "daily" },
            { task_name: "Kiem tra sau benh", frequency: "daily" },
          ],
          observation_required: [
            { key: "has_true_leaf", label: "Đã có lá thật?" },
          ],
        },
        {
          stage_number: 2,
          name: "Giai doan 2",
          day_start: 22,
          day_end: 30,
          weight: 25,
        },
        {
          stage_number: 3,
          name: "Giai doan 3",
          day_start: 31,
          day_end: 40,
          weight: 25,
        },
      ],
      status: "active",
    });

    log("Created PlantTemplate", template._id.toString());
  } else {
    log("Found PlantTemplate", template._id.toString());
  }

  // 3) Compute dates: vietnamToday, yesterday (VN midnight), and planted_date so that day-20 == yesterday
  const vietnamToday = getVietnamToday();
  const yesterday = new Date(vietnamToday);
  yesterday.setDate(yesterday.getDate() - 1);

  // planted_date such that day 20 corresponds to `yesterday`
  const plantedDate = new Date(yesterday);
  plantedDate.setDate(plantedDate.getDate() - (20 - 1)); // -19

  log("vietnamToday", vietnamToday.toISOString().split("T")[0]);
  log("yesterday", yesterday.toISOString().split("T")[0]);
  log(
    "plantedDate (so that day20 == yesterday)",
    plantedDate.toISOString().split("T")[0]
  );

  // 4) Create a notebook for user with a daily_checklist item created yesterday and not completed
  let notebook = await Notebook.create({
    user_id: user._id,
    notebook_name: "HungBe Test Notebook",
    plant_type: "Hung Be",
    template_id: template._id,
    planted_date: plantedDate,
    // daily checklist with one task created yesterday (day20) and not completed
    daily_checklist: [
      {
        task_name: "Tuoi nuoc - Day 20",
        description: "Overdue task from day 20",
        is_completed: false,
        completed_at: null,
        priority: "medium",
        frequency: "daily",
        status: "pending",
        overdue_at: null,
        created_at: yesterday,
      },
    ],
    // Initialize stages_tracking with stage 1 current
    stages_tracking: [
      {
        stage_number: 1,
        stage_name: "Giai doan 1 (test)",
        started_at: plantedDate, // approximate
        is_current: true,
        status: "active",
        missed_days: 0,
        notifications_sent: [],
        completed_tasks: [],
        observations: [],
        daily_logs: [],
        overdue_tasks: [],
        overdue_summary: {},
      },
    ],
  });

  log("Created notebook", notebook._id.toString());

  // 5) Trigger a reminder manually by calling the notification helper correctly
  log("Sending daily reminder notification (simulating job)...");
  await sendDailyReminderNotification({
    userId: user._id,
    notebookId: notebook._id,
    notebookName: notebook.notebook_name,
    incompleteTasks: 1,
  });

  // 6) Verify notification exists
  const notes = await Notification.find({ user_id: user._id })
    .sort({ createdAt: -1 })
    .limit(5);
  log(
    "Notifications for user (latest):",
    notes.map((n) => ({ type: n.type, title: n.title, createdAt: n.createdAt }))
  );

  // 7) Simulate user clicking notification and going to overdue tasks page -> complete the overdue task
  log("Marking the overdue task as completed (day-20)...");
  // Reload notebook
  notebook = await Notebook.findById(notebook._id);
  const task = notebook.daily_checklist.find((t) =>
    t.task_name.includes("Day 20")
  );
  if (!task) {
    throw new Error("Test task not found in notebook.daily_checklist");
  }

  task.is_completed = true;
  task.completed_at = new Date();
  task.status = "completed";

  // Update stage tracking: add to completed_tasks and add daily_log for day-20 (yesterday) 100%
  const stageTrack = notebook.stages_tracking.find((s) => s.stage_number === 1);
  stageTrack.completed_tasks.push({
    task_name: task.task_name,
    completed_at: task.completed_at,
  });
  stageTrack.daily_logs.push({ date: yesterday, daily_progress: 100 });

  await notebook.save();
  log("Saved notebook after completing day-20 task");

  // 8) Recompute current stage completion and overall progress
  notebook = await Notebook.findById(notebook._id).populate("template_id");
  const stageCompletionAfterDay20 = await notebook.getCurrentStageCompletion();
  const progressAfterDay20 = await notebook.updateProgress(
    notebook.template_id.stages
  );
  log(
    "Stage completion after completing day-20:",
    stageCompletionAfterDay20 + "%"
  );
  log("Notebook progress after day-20 completion:", progressAfterDay20 + "%");

  // 9) Simulate day-21 task created today and user completes it
  const today = getVietnamToday();
  log("Simulating day-21 task for today:", today.toISOString().split("T")[0]);

  notebook.daily_checklist.push({
    task_name: "Tuoi nuoc - Day 21",
    description: "Task for day 21",
    is_completed: true,
    completed_at: new Date(),
    priority: "medium",
    frequency: "daily",
    status: "completed",
    created_at: today,
  });

  // Add daily_log for today with 100%
  const stageTrack2 = notebook.stages_tracking.find(
    (s) => s.stage_number === 1
  );
  stageTrack2.daily_logs.push({ date: today, daily_progress: 100 });
  stageTrack2.completed_tasks.push({
    task_name: "Tuoi nuoc - Day 21",
    completed_at: new Date(),
  });

  // As today is day_end for stage 1, set an observation (will be used to allow transition)
  stageTrack2.observations.push({
    key: "has_true_leaf",
    value: true,
    observed_at: new Date(),
  });

  // Mark stage completed and set completed_at
  stageTrack2.completed_at = new Date();
  stageTrack2.status = "completed";
  stageTrack2.is_current = false;

  // Move notebook current_stage forward
  notebook.current_stage = 2;

  await notebook.save();
  log("Saved notebook after completing day-21 task and marking stage complete");

  // 10) Recompute progress
  const refreshed = await Notebook.findById(notebook._id).populate(
    "template_id"
  );
  const finalStageCompletion = await refreshed.getCurrentStageCompletion();
  const finalProgress = await refreshed.updateProgress(
    refreshed.template_id.stages
  );

  log(
    "Final stage completion (should reflect new current stage calculations):",
    finalStageCompletion + "%"
  );
  log(
    "Final notebook progress (after completing stage 1):",
    finalProgress + "%"
  );

  log("Test flow completed — check DB for notifications and notebook updates.");

  await mongoose.connection.close();
  process.exit(0);
};

main().catch((err) => {
  console.error("Test script error:", err);
  process.exit(1);
});
