import React from "react";

// Step 2: Stages Setup
export const Step2Stages = ({ stages, addStage, updateStage, removeStage }) => (
  <div className="step-stages">
    <div className="step-header">
      <h2>Giai đoạn phát triển</h2>
      <p className="hint">Template cần có ít nhất 3 giai đoạn</p>
    </div>

    {stages.map((stage, index) => (
      <div key={index} className="stage-card">
        <div className="stage-card-header">
          <h3>Giai đoạn {stage.stage_number}</h3>
          {stages.length > 3 && (
            <button
              type="button"
              className="btn-icon btn-danger"
              onClick={() => removeStage(index)}
              title="Xóa giai đoạn"
            >
              🗑️
            </button>
          )}
        </div>

        <div className="form-row">
          <div className="form-group flex-1">
            <label>
              Tên giai đoạn <span className="required">*</span>
            </label>
            <input
              type="text"
              className="form-input"
              placeholder="Ví dụ: Nảy mầm"
              value={stage.name}
              onChange={(e) => updateStage(index, "name", e.target.value)}
            />
          </div>
        </div>

        <div className="form-group">
          <label>Mô tả giai đoạn</label>
          <textarea
            className="form-textarea"
            rows="2"
            placeholder="Mô tả chi tiết về giai đoạn này..."
            value={stage.description}
            onChange={(e) => updateStage(index, "description", e.target.value)}
          />
        </div>

        <div className="form-row">
          <div className="form-group">
            <label>
              Ngày bắt đầu <span className="required">*</span>
            </label>
            <input
              type="number"
              className="form-input"
              min="1"
              value={stage.day_start}
              onChange={(e) =>
                updateStage(index, "day_start", parseInt(e.target.value))
              }
            />
          </div>

          <div className="form-group">
            <label>
              Ngày kết thúc <span className="required">*</span>
            </label>
            <input
              type="number"
              className="form-input"
              min={stage.day_start + 1}
              value={stage.day_end}
              onChange={(e) =>
                updateStage(index, "day_end", parseInt(e.target.value))
              }
            />
          </div>

          <div className="form-group">
            <label>Tổng ngày</label>
            <div className="form-static">
              {stage.day_end - stage.day_start + 1} ngày
            </div>
          </div>
        </div>

        <div className="form-group">
          <label>Ảnh mẫu giai đoạn (URL)</label>
          <input
            type="text"
            className="form-input"
            placeholder="https://example.com/stage-image.jpg"
            value={stage.stage_image || ""}
            onChange={(e) => updateStage(index, "stage_image", e.target.value)}
          />
          {stage.stage_image && (
            <div className="image-preview">
              <img
                src={stage.stage_image}
                alt={`Stage ${stage.stage_number}`}
              />
            </div>
          )}
        </div>
      </div>
    ))}

    <button
      type="button"
      className="btn btn-outline btn-block"
      onClick={addStage}
    >
      + Thêm giai đoạn
    </button>
  </div>
);

// Step 3: Tasks (Autogenerated Tasks)
export const Step3Tasks = ({
  stages,
  addTaskToStage,
  updateTask,
  removeTask,
}) => (
  <div className="step-tasks">
    <div className="step-header">
      <h2>Nhiệm vụ tự động</h2>
      <p className="hint">
        Các nhiệm vụ này sẽ được tự động sinh ra cho người dùng mỗi ngày
      </p>
    </div>

    {stages.map((stage, stageIndex) => (
      <div key={stageIndex} className="stage-section">
        <div className="stage-section-header">
          <h3>
            Giai đoạn {stage.stage_number}: {stage.name}
          </h3>
          <span className="badge">
            {stage.autogenerated_tasks?.length || 0} nhiệm vụ
          </span>
        </div>

        {stage.autogenerated_tasks?.map((task, taskIndex) => (
          <div key={taskIndex} className="task-card">
            <div className="task-card-header">
              <span className="task-number">Nhiệm vụ {taskIndex + 1}</span>
              <button
                type="button"
                className="btn-icon btn-sm"
                onClick={() => removeTask(stageIndex, taskIndex)}
              >
                ×
              </button>
            </div>

            <div className="form-row">
              <div className="form-group flex-2">
                <label>Tên nhiệm vụ</label>
                <input
                  type="text"
                  className="form-input"
                  placeholder="Ví dụ: Tưới nước"
                  value={task.task_name}
                  onChange={(e) =>
                    updateTask(
                      stageIndex,
                      taskIndex,
                      "task_name",
                      e.target.value
                    )
                  }
                />
              </div>

              <div className="form-group flex-1">
                <label>Tần suất</label>
                <select
                  className="form-select"
                  value={task.frequency}
                  onChange={(e) =>
                    updateTask(
                      stageIndex,
                      taskIndex,
                      "frequency",
                      e.target.value
                    )
                  }
                >
                  <option value="daily">Hàng ngày</option>
                  <option value="every_2_days">2 ngày/lần</option>
                  <option value="every_3_days">3 ngày/lần</option>
                  <option value="weekly">Hàng tuần</option>
                </select>
              </div>

              <div className="form-group flex-1">
                <label>Độ ưu tiên</label>
                <select
                  className="form-select"
                  value={task.priority}
                  onChange={(e) =>
                    updateTask(
                      stageIndex,
                      taskIndex,
                      "priority",
                      e.target.value
                    )
                  }
                >
                  <option value="low">Thấp</option>
                  <option value="medium">Trung bình</option>
                  <option value="high">Cao</option>
                </select>
              </div>
            </div>

            <div className="form-group">
              <label>Mô tả</label>
              <textarea
                className="form-textarea"
                rows="2"
                placeholder="Mô tả chi tiết nhiệm vụ..."
                value={task.description}
                onChange={(e) =>
                  updateTask(
                    stageIndex,
                    taskIndex,
                    "description",
                    e.target.value
                  )
                }
              />
            </div>

            <div className="form-group">
              <label>Ảnh minh họa (URL)</label>
              <input
                type="text"
                className="form-input"
                placeholder="https://example.com/task-image.jpg"
                value={task.illustration_image || ""}
                onChange={(e) =>
                  updateTask(
                    stageIndex,
                    taskIndex,
                    "illustration_image",
                    e.target.value
                  )
                }
              />
            </div>
          </div>
        ))}

        <button
          type="button"
          className="btn btn-outline btn-sm"
          onClick={() => addTaskToStage(stageIndex)}
        >
          + Thêm nhiệm vụ
        </button>
      </div>
    ))}
  </div>
);

// Step 4: Observations
export const Step4Observations = ({
  stages,
  addObservationToStage,
  updateObservation,
  removeObservation,
}) => (
  <div className="step-observations">
    <div className="step-header">
      <h2>Điều kiện quan sát</h2>
      <p className="hint">
        Các điều kiện quan sát nhị phân (Có/Không) để xác định chuyển giai đoạn
      </p>
    </div>

    {stages.map((stage, stageIndex) => (
      <div key={stageIndex} className="stage-section">
        <div className="stage-section-header">
          <h3>
            Giai đoạn {stage.stage_number}: {stage.name}
          </h3>
          <span className="badge">
            {stage.observation_required?.length || 0} điều kiện
          </span>
        </div>

        {stage.observation_required?.map((obs, obsIndex) => (
          <div key={obsIndex} className="observation-card">
            <div className="observation-card-header">
              <span className="obs-number">Điều kiện {obsIndex + 1}</span>
              <button
                type="button"
                className="btn-icon btn-sm"
                onClick={() => removeObservation(stageIndex, obsIndex)}
              >
                ×
              </button>
            </div>

            <div className="form-row">
              <div className="form-group flex-1">
                <label>Key (định danh)</label>
                <input
                  type="text"
                  className="form-input"
                  placeholder="Ví dụ: has_sprout"
                  value={obs.key}
                  onChange={(e) =>
                    updateObservation(
                      stageIndex,
                      obsIndex,
                      "key",
                      e.target.value
                    )
                  }
                />
                <small className="hint">Dùng snake_case, không dấu</small>
              </div>

              <div className="form-group flex-1">
                <label>Câu hỏi hiển thị</label>
                <input
                  type="text"
                  className="form-input"
                  placeholder="Ví dụ: Đã nảy mầm?"
                  value={obs.label}
                  onChange={(e) =>
                    updateObservation(
                      stageIndex,
                      obsIndex,
                      "label",
                      e.target.value
                    )
                  }
                />
              </div>
            </div>

            <div className="form-group">
              <label>Mô tả</label>
              <input
                type="text"
                className="form-input"
                placeholder="Mô tả chi tiết để user dễ quan sát"
                value={obs.description}
                onChange={(e) =>
                  updateObservation(
                    stageIndex,
                    obsIndex,
                    "description",
                    e.target.value
                  )
                }
              />
            </div>
          </div>
        ))}

        <button
          type="button"
          className="btn btn-outline btn-sm"
          onClick={() => addObservationToStage(stageIndex)}
        >
          + Thêm điều kiện quan sát
        </button>
      </div>
    ))}
  </div>
);

// Step 5: Rules & Review
export const Step5Review = ({
  formData,
  handleRuleChange,
  handleInputChange,
}) => (
  <div className="step-review">
    <div className="step-header">
      <h2>Quy tắc & Xác nhận</h2>
    </div>

    <div className="section">
      <h3>Quy tắc xử lý trễ hạn</h3>

      <div className="form-row">
        <div className="form-group">
          <label>Số ngày cho phép trễ</label>
          <input
            type="number"
            className="form-input"
            min="0"
            value={formData.rules.safe_delay_days}
            onChange={(e) =>
              handleRuleChange("safe_delay_days", parseInt(e.target.value))
            }
          />
          <small className="hint">
            Nếu user trễ quá số ngày này, hệ thống sẽ cảnh báo
          </small>
        </div>

        <div className="form-group">
          <label>Số ngày cảnh báo</label>
          <input
            type="number"
            className="form-input"
            min="0"
            value={formData.rules.warning_days}
            onChange={(e) =>
              handleRuleChange("warning_days", parseInt(e.target.value))
            }
          />
          <small className="hint">Cảnh báo user khi trễ từ ngày này</small>
        </div>
      </div>

      <div className="form-group">
        <label className="checkbox-label">
          <input
            type="checkbox"
            checked={formData.rules.auto_skip}
            onChange={(e) => handleRuleChange("auto_skip", e.target.checked)}
          />
          <span>Tự động skip giai đoạn nếu quá trễ</span>
        </label>
      </div>
    </div>

    <div className="section">
      <h3>Trạng thái & Ghi chú</h3>

      <div className="form-group">
        <label>Trạng thái</label>
        <select
          className="form-select"
          value={formData.status}
          onChange={(e) => handleInputChange("status", e.target.value)}
        >
          <option value="draft">Nháp (Draft)</option>
          <option value="active">Hoạt động (Active)</option>
        </select>
      </div>

      <div className="form-group">
        <label>Ghi chú</label>
        <textarea
          className="form-textarea"
          rows="3"
          placeholder="Ghi chú thêm về template này..."
          value={formData.notes}
          onChange={(e) => handleInputChange("notes", e.target.value)}
        />
      </div>
    </div>

    <div className="section">
      <h3>Tổng quan Template</h3>
      <div className="summary-grid">
        <div className="summary-item">
          <div className="summary-label">Tên template</div>
          <div className="summary-value">{formData.template_name}</div>
        </div>
        <div className="summary-item">
          <div className="summary-label">Nhóm cây</div>
          <div className="summary-value">{formData.plant_group}</div>
        </div>
        <div className="summary-item">
          <div className="summary-label">Số giai đoạn</div>
          <div className="summary-value">{formData.stages.length}</div>
        </div>
        <div className="summary-item">
          <div className="summary-label">Tổng ngày</div>
          <div className="summary-value">
            {formData.stages.length > 0
              ? Math.max(...formData.stages.map((s) => s.day_end))
              : 0}{" "}
            ngày
          </div>
        </div>
        <div className="summary-item">
          <div className="summary-label">Tổng nhiệm vụ</div>
          <div className="summary-value">
            {formData.stages.reduce(
              (sum, stage) => sum + (stage.autogenerated_tasks?.length || 0),
              0
            )}
          </div>
        </div>
        <div className="summary-item">
          <div className="summary-label">Tổng điều kiện</div>
          <div className="summary-value">
            {formData.stages.reduce(
              (sum, stage) => sum + (stage.observation_required?.length || 0),
              0
            )}
          </div>
        </div>
      </div>
    </div>
  </div>
);
